server:
  port: 8085

spring:
  profiles:
    active: dev
  application:
    name: javaweb-system

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

# MyBatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.javaweb.**.**.mapper
  configuration:
    # 开启驼峰命名法
    map-underscore-to-camel-case: true
    use-generated-keys: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

## 认证配置
security:
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://javaweb-auth/oauth/user
      token-info-uri: http://javaweb-auth/oauth/check_token
    client:
      client-id: javaweb
      client-secret: 123456
      access-token-uri: http://javaweb-auth/oauth/token
      grant-type: client_credentials,password
      scope: server