spring:
  redis:
    host: localhost
    port: 6379
    password:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: javaweb-auth
          uri: lb://javaweb-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        # 系统模块
        - id: javaweb-system
          uri: lb://javaweb-system
          predicates:
            - Path=/api/system/**
          filters:
            - StripPrefix=2
        # 代码生成器
        - id: javaweb-generator
          uri: lb://javaweb-generator
          predicates:
            - Path=/api/generator/**
          filters:
            - StripPrefix=2